DECODING_CODES = {
    '00' : 'Ok',
    '01' : 'User added',
    '02' : 'User added with registration',
    '03' : 'User is not exist',
    '04' : 'User is alredy exist',
    '05' : 'User updated',
    '06' : 'User didn\'t update',
    '07' : 'Empty or invalid username/password',
    '08' : 'User deleted',
    '09' : 'User didn\'t delete',
    '10' : '',
    '11' : 'Card added',
    '12' : '',
    '13' : 'Card is not exist',
    '14' : 'Card is alredy exist',
    '15' : 'Card update',
    '16' : 'Card didn\'t update',
    '17' : '',
    '18' : 'Card deleted',
    '19' : 'Card didn\'t delete',
}
TEXT_IF_NO_CODE = 'No error message'
